server:
  port: 8888
spring:
  cloud:
    config:
      server:
        git:
          #uri: file:C:/dev/git/micro-services
          uri: https://github.com/isilona/micro-services/
          search-paths:
          - configuration-properties
  application:
    name: configuration